Done 1st home work
htmlacademy-htmlcss/2108721-device-35 pull request #2
Opened 2022-09-29 09:23 UTC by Grikus

Пока смотри только разметку, разметил каталог, индекс, модалку, и выскакивающее окошко с каталогом, который в хедере. Стили не смотри, надо подправлять кое что.

2022-10-02 12:17 UTC, Kartaviy-arteom requested changes
у тебя получаются одни и те же картинки в обоих дирректориях. Тогда тебе лучше разделить по-другому, по блокам или собрать все иконки в одном месте. И тебе не нужно экспортировать иконки с прозрачностью
asdfasdd.html нужно удалить

2022-10-02 12:17 UTC, Kartaviy-arteom commented on index.html
> +            <svg aria-hidden="true" focusable="false" width="145" height="37" fill="none"
role="img" и aria-label

2022-10-02 12:17 UTC, Kartaviy-arteom commented on index.html
> +          <nav class="navigation-column">
я бы здесь выделил в nav каталог, доставка, гарантия, контакты

2022-10-02 12:17 UTC, Kartaviy-arteom commented on index.html
> +          <h2 class="visually-hidden">Горячие предложения!</h2>
тебе нужно соблюсти иерархию заголовков
Внутри списка могут быть только элементы списка
Слайдер в мейне будет

2022-10-02 12:17 UTC, Kartaviy-arteom commented on index.html
> +              </button>
это кнопки смены слайдов

2022-10-02 12:17 UTC, Kartaviy-arteom commented on index.html
> +              </div>
зачем тебе этот див?

2022-10-02 12:17 UTC, Kartaviy-arteom commented on index.html
> +              </button>
это смена слайдев

2022-10-02 12:17 UTC, Kartaviy-arteom commented on index.html
> +                </dl>
тебе не нужен список определений для каждого значения

2022-10-02 12:17 UTC, Kartaviy-arteom commented on index.html
> +        <ol class="slider-pagination">
будет внутри слайдера, позиционируется относительно слайдера

2022-10-02 12:17 UTC, Kartaviy-arteom commented on index.html
> +        <h1 class="visually-hidden">
должен быть первым заголовком на странице

2022-10-02 12:17 UTC, Kartaviy-arteom commented on index.html
> +                  <img src=".//images/index/copter-icon.svg" width="132" height="69" alt="квадрокоптеры.">
в критериях есть про одинаковое описание у картинок

2022-10-02 12:17 UTC, Kartaviy-arteom commented on index.html
> +            <div class="visually-hidden guarantee-description description">
тебе не нужен тут visually-hidden

2022-10-02 12:17 UTC, Kartaviy-arteom commented on index.html
> +          <h2 class="visually-hidden">Окно доставки товаров.</h2>
неинформативный заголовок

2022-10-02 12:17 UTC, Kartaviy-arteom commented on index.html
> +          <button class="modal-icon-index" type="button"></button>
для чего эта кнопка?

2022-10-02 12:17 UTC, Kartaviy-arteom commented on index.html
> +          <a class="footer-logo" href="index.html"></a>
логотип контентное изоражение

2022-10-02 12:17 UTC, Kartaviy-arteom commented on index.html
> +          <a class="author-link" href="https://htmlacademy.ru/" target="_blank">
логотип контентный

2022-10-02 13:47 UTC, Grikus commented on index.html
> +            <svg aria-hidden="true" focusable="false" width="145" height="37" fill="none"
все что в шапке твое исправил. не понял что делать с aria-label?

2022-10-02 13:47 UTC, Grikus commented on index.html
> +              </button>
то есть проблема в названии*?
 Следующее фото
Предыдущее фото

2022-10-02 13:55 UTC, Grikus commented on index.html
> +              </div>
убрал

2022-10-02 15:56 UTC, Grikus commented on index.html
> +            <div class="visually-hidden guarantee-description description">
убрал

2022-10-02 15:58 UTC, Grikus commented on index.html
> +          <nav class="navigation-column">
сделал

2022-10-02 15:59 UTC, Grikus commented on index.html
> +          <nav class="navigation-column">
есть возмодность оставить? иначе весь хедер перекраивать придется...
вместе со стилями

2022-10-02 16:00 UTC, Grikus commented on index.html
> +          <h2 class="visually-hidden">Горячие предложения!</h2>
можно ли оставить слайдер как есть? тоже придется все перекраивать

2022-10-02 16:05 UTC, Grikus commented on index.html
> +          <button class="modal-icon-index" type="button"></button>
вызывает модальное окно

2022-10-03 08:14 UTC, Grikus commented on index.html
> +          <h2 class="visually-hidden">Окно доставки товаров.</h2>
исправил

2022-10-03 08:23 UTC, Grikus commented on index.html
> +          <a class="author-link" href="https://htmlacademy.ru/" target="_blank">
исправил

2022-10-03 08:23 UTC, Grikus commented on index.html
> +          <a class="footer-logo" href="index.html"></a>
исправил

2022-10-03 08:24 UTC, Grikus commented on index.html
> +          <h2 class="visually-hidden">Горячие предложения!</h2>
исравил

2022-10-03 09:30 UTC, Grikus commented on index.html
> +              </button>
не понял

2022-10-03 09:31 UTC, Grikus commented on index.html
> +                </dl>
тоже не понял, типа второй dl лишний?

2022-10-03 09:31 UTC, Grikus commented on index.html
> +        <ol class="slider-pagination">
исправил

2022-10-03 09:31 UTC, Grikus commented on index.html
> +        <h1 class="visually-hidden">
исправил

2022-10-03 09:38 UTC, Grikus commented on index.html
> +                  <img src=".//images/index/copter-icon.svg" width="132" height="69" alt="квадрокоптеры.">
исправил

2022-10-03 09:40 UTC, Grikus commented on index.html
> +            <svg aria-hidden="true" focusable="false" width="145" height="37" fill="none"
исправил

2022-10-03 14:46 UTC, Kartaviy-arteom commented on index.html
> +          <nav class="navigation-column">
пока оставь

2022-10-03 14:46 UTC, Kartaviy-arteom commented on index.html
> +              </button>
еще они должны быть одни на весь слайдер, не в каждом слайде

2022-10-03 14:47 UTC, Kartaviy-arteom commented on index.html
> +          <button class="modal-icon-index" type="button"></button>
кнопкам нужно описание

2022-10-03 18:38 UTC, Grikus commented on index.html
> +              </button>
исправил

2022-10-03 18:39 UTC, Grikus commented on index.html
> +          <button class="modal-icon-index" type="button"></button>
добавил

2022-10-06 07:42 UTC, Grikus commented on index.html
> +          <nav class="navigation-column">
переделал разметку

2022-10-06 07:54 UTC, romantsarew commented on index.html
> +        <ol class="slider-pagination">
валидацию не проходит когда вкладываешь список в список

2022-10-06 09:44 UTC, closed without merging

2022-10-06 09:49 UTC, Grikus reviewed
done all