index html catalog html
htmlacademy-htmlcss/2108721-device-35 pull request #3
Opened 2022-10-06 09:56 UTC by Grikus

комит для того чтоб обновить пул реквест

2022-10-08 08:52 UTC, Kartaviy-arteom requested changes
тебе не нужно экспортировать иконки с прозрачностью

2022-10-08 08:52 UTC, Kartaviy-arteom commented on catalog.html
> +            <button class="button-usual show-results" type="submit">Показать</a>
это что-то очень странное

2022-10-08 08:52 UTC, Kartaviy-arteom commented on catalog.html
> +            <fieldset class="catalog-price">
должна быть форма

2022-10-08 08:52 UTC, Kartaviy-arteom commented on catalog.html
> +                <button class="search-button" type="button" value="кнопка поиска на сайте">Найти</button>
type submit

2022-10-08 08:52 UTC, Kartaviy-arteom commented on catalog.html
> +          <ul class="personal-menu">
в список мы объединяем однородные элементы

2022-10-08 08:52 UTC, Kartaviy-arteom commented on catalog.html
> +                    <a class="subcatalog-link" href="catalog.html">Виртуальная реальность</a>
лучше в href проставить #, это все-таки разные страницы

2022-10-08 08:52 UTC, Kartaviy-arteom commented on catalog.html
> +          <strong class="breadcrumbs-title">Моноподы для селфи</strong>
это основной заголовок, это страница моноподов

2022-10-08 08:52 UTC, Kartaviy-arteom commented on catalog.html
> +            <span class="filter-divider"></span>
это не нужный элемент

2022-10-08 08:52 UTC, Kartaviy-arteom commented on catalog.html
> +                    <input class="price-input input-from" type="number" value="0" name="min-price">
input не связан с label

2022-10-08 08:52 UTC, Kartaviy-arteom commented on catalog.html
> +                    <input class="price-input input-to" type="number" value="5000" name="max-price">
input не связан с label

2022-10-08 08:52 UTC, Kartaviy-arteom commented on catalog.html
> +                    <input class="visually-hidden" type="checkbox" name="black" checked tabindex="0">
input не нужен tabindex

2022-10-08 08:52 UTC, Kartaviy-arteom commented on catalog.html
> +                    <span class="sort-check" tabindex="0">
и тут не нужен

2022-10-08 08:52 UTC, Kartaviy-arteom commented on catalog.html
> +                    <input class="visually-hidden" type="radio" name="it-isn't" value="no">
радиокнопки не связаны

2022-10-08 08:52 UTC, Kartaviy-arteom commented on catalog.html
> +            <h3 class="visually-hidden">Результат сортировки.</h3>
структура заголовков, почему у фильтров h2, тут h3

2022-10-08 08:52 UTC, Kartaviy-arteom commented on catalog.html
> +                    </dl>
неуместное использование тегов

2022-10-08 08:52 UTC, Kartaviy-arteom commented on catalog.html
> +                <button class="pagination-button pagination-back" type="button">Назад</button>
ссылка

2022-10-08 08:52 UTC, Kartaviy-arteom commented on catalog.html
> +                <button class="pagination-button pagination-forward" type="button">Вперёд</button>
ссылка

2022-10-08 08:52 UTC, Kartaviy-arteom commented on catalog.html
> +            <svg width="145" height="36" viewBox="0 0 145 36" fill="none" xmlns="http://www.w3.org/2000/svg">
role="img" и aria-label на теге svg не на отдельном пути

2022-10-08 08:52 UTC, Kartaviy-arteom commented on catalog.html
> +              aria-label="ссылка к разработчикам сайта желтого цвета.">
aria-label не уместный

2022-10-08 08:52 UTC, Kartaviy-arteom commented on index.html
> +    <h1 class="visually-hidden">Добро пожаловать на сайт магазина Девайс.</h1>
лучше разместить в main

2022-10-08 08:52 UTC, Kartaviy-arteom commented on index.html
> +                    <dd class="main-text parameters-text">Радиус поражения</dd>
dt здесь будет "радиус поражения"

2022-10-08 08:52 UTC, Kartaviy-arteom commented on index.html
> +              <img class="slider-image" src="./images/bracelet-photo.png" alt="фото фитнесс браслета черного цвета."
в alt к картинке не нужно писать, что это картинка или изображение, это и так понятно

2022-10-08 08:52 UTC, Kartaviy-arteom commented on index.html
> +                </div>
можно в div ее не оборачивать

2022-10-08 08:52 UTC, Kartaviy-arteom commented on index.html
> +                  value="кнопка открытия блока с описанием">Доставка</button>
зачем здесь  value?

2022-10-08 08:52 UTC, Kartaviy-arteom commented on index.html
> +          <button class="modal-button" type="button">Доставим редкий товар под заказ
должна быть одна кнопка

2022-10-08 08:52 UTC, Kartaviy-arteom commented on index.html
> +        <section class="contact-block">
это может быть div с двумя секциями, или секция внутри которой рядом две секции

2022-10-10 06:24 UTC, Grikus commented on catalog.html
> +            <button class="button-usual show-results" type="submit">Показать</a>
исправил

2022-10-10 06:24 UTC, Grikus commented on catalog.html
> +            <fieldset class="catalog-price">
исправил

2022-10-10 06:25 UTC, Grikus commented on catalog.html
> +                <button class="search-button" type="button" value="кнопка поиска на сайте">Найти</button>
исправил

2022-10-10 06:36 UTC, Grikus commented on catalog.html
> +          <ul class="personal-menu">
исправил

2022-10-10 06:37 UTC, Grikus commented on catalog.html
> +                    <a class="subcatalog-link" href="catalog.html">Виртуальная реальность</a>
исправил

2022-10-10 06:40 UTC, Grikus commented on index.html
> +              <img class="slider-image" src="./images/bracelet-photo.png" alt="фото фитнесс браслета черного цвета."
исправил

2022-10-10 06:42 UTC, Grikus commented on catalog.html
> +          <strong class="breadcrumbs-title">Моноподы для селфи</strong>
исправил

2022-10-10 06:55 UTC, Grikus commented on catalog.html
> +            <span class="filter-divider"></span>
убрал

2022-10-10 07:46 UTC, Grikus commented on catalog.html
> +                    <input class="price-input input-from" type="number" value="0" name="min-price">
исправил

2022-10-10 07:46 UTC, romantsarew commented on catalog.html
> +                    <input class="price-input input-to" type="number" value="5000" name="max-price">
исправил

2022-10-10 07:47 UTC, Grikus commented on catalog.html
> +                    <input class="visually-hidden" type="checkbox" name="black" checked tabindex="0">
исправил

2022-10-10 07:48 UTC, Grikus commented on catalog.html
> +                    <span class="sort-check" tabindex="0">
исправил

2022-10-10 07:48 UTC, Grikus commented on catalog.html
> +                    <input class="visually-hidden" type="radio" name="it-isn't" value="no">
исправил

2022-10-10 07:49 UTC, Grikus commented on catalog.html
> +            <h3 class="visually-hidden">Результат сортировки.</h3>
исправил

2022-10-10 07:50 UTC, Grikus commented on catalog.html
> +                <button class="pagination-button pagination-back" type="button">Назад</button>
исправил

2022-10-10 07:50 UTC, Grikus commented on catalog.html
> +                <button class="pagination-button pagination-forward" type="button">Вперёд</button>
исправил

2022-10-10 07:51 UTC, Grikus commented on catalog.html
> +            <svg width="145" height="36" viewBox="0 0 145 36" fill="none" xmlns="http://www.w3.org/2000/svg">
исправил

2022-10-10 07:53 UTC, Grikus commented on index.html
> +    <h1 class="visually-hidden">Добро пожаловать на сайт магазина Девайс.</h1>
сделал

2022-10-10 07:54 UTC, Grikus commented on index.html
> +                    <dd class="main-text parameters-text">Радиус поражения</dd>
исправил

2022-10-10 07:58 UTC, romantsarew commented on index.html
> +                </div>
исправил

2022-10-10 07:59 UTC, Grikus commented on index.html
> +                  value="кнопка открытия блока с описанием">Доставка</button>
убрал

2022-10-10 08:01 UTC, Grikus commented on index.html
> +          <button class="modal-button" type="button">Доставим редкий товар под заказ
исправил

2022-10-10 08:03 UTC, Grikus commented on index.html
> +        <section class="contact-block">
исправил, но не понял почему так?

2022-10-10 08:27 UTC, Grikus commented on catalog.html
> +                    </dl>
исправил

2022-10-10 08:28 UTC, Grikus commented on catalog.html
> +              aria-label="ссылка к разработчикам сайта желтого цвета.">
поменял

2022-10-13 18:47 UTC, Kartaviy-arteom requested changes

2022-10-13 18:47 UTC, Kartaviy-arteom commented on index.html
> +              </li>
</li> лишняя

2022-10-13 18:47 UTC, Kartaviy-arteom commented on index.html
> +                    <button class="popover-close-button button button-light" type="button">Открыть корзину</button>
ссылка

2022-10-13 18:47 UTC, Kartaviy-arteom commented on index.html
> +                </div>
лучше убрать в декоративную графику

2022-10-13 18:47 UTC, Kartaviy-arteom commented on index.html
> +                  value="кнопка открытия блока с описанием">Доставка</button>
value осталось

2022-10-13 18:47 UTC, Kartaviy-arteom commented on index.html
> +          <div class="modal-icon-index"></div>
modal-icon-index зачем это тут?

2022-10-13 18:47 UTC, Kartaviy-arteom commented on index.html
> +                    <dt class="main-text parameters-text">Материал</dt>
что бы было валидно термин должен быть перед определением, в отображения порядок стилями поменять

2022-10-13 18:47 UTC, Kartaviy-arteom commented on index.html
> +              aria-label="ссылка к разработчикам сайта желтого цвета.">
aria-label плохое значение

2022-10-13 18:47 UTC, Kartaviy-arteom commented on index.html
> +          <button class="modal-close-button" type="button" value="закрыть окно">
value не  нужен

2022-10-13 18:47 UTC, Kartaviy-arteom commented on catalog.html
> +                <button class="sort-button button-up" type="button" alt="сортировка по возрастанию">
alt невалидный атрибут

2022-10-13 18:47 UTC, Kartaviy-arteom commented on catalog.html
> +                <button class="load-more" type="button">Загрузить ещЁ</button>
ul не может быть родителем у кнопки

2022-10-13 18:48 UTC, merged

2022-10-16 17:12 UTC, Grikus commented on index.html
> +              </li>
исправил

2022-10-16 17:14 UTC, Grikus commented on index.html
> +                    <button class="popover-close-button button button-light" type="button">Открыть корзину</button>
сделал

2022-10-16 17:23 UTC, Grikus commented on index.html
> +                </div>
почему? 
тут проблема я тебе писал вначале, что нужно задать бекграунд с размерами и цветом, а картинку отдельно, а теперь нужно будет химичить что то другое, чтоб картинка была нужного размера в нужном месте еще и в css, может лучше оставить?

2022-10-16 17:24 UTC, Grikus commented on index.html
> +                  value="кнопка открытия блока с описанием">Доставка</button>
убрал

2022-10-16 17:26 UTC, Grikus commented on index.html
> +          <div class="modal-icon-index"></div>
потому что в стайлгайде она имеет другие состояния, нежели весь остальной блок, и мне нужно чтоб эта иконка желтая была отдельно

2022-10-16 17:31 UTC, Grikus commented on index.html
> +                    <dt class="main-text parameters-text">Материал</dt>
сделал

2022-10-16 17:32 UTC, Grikus commented on index.html
> +              aria-label="ссылка к разработчикам сайта желтого цвета.">
исправил

2022-10-16 17:33 UTC, Grikus commented on catalog.html
> +                <button class="sort-button button-up" type="button" alt="сортировка по возрастанию">
исправил

2022-10-16 17:37 UTC, Grikus commented on catalog.html
> +                <button class="load-more" type="button">Загрузить ещЁ</button>
исправил

2022-10-16 17:37 UTC, Grikus commented on index.html
> +          <button class="modal-close-button" type="button" value="закрыть окно">
убрал